# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02d9211479058fe22d7554bbe3b43db1fa9b9833fcf4c08f2f418b82419dfdf98b31f220990bc7a966b4a81a097a4da4ad217eb2145657309e9848d1349e8f17

test:
  secret_key_base: 31eb6985209e0e9c8801923e081c468680124c4437f4c4c45a8c5241b78c8fd912d79e6bc2e8af0873c26c0367244776efa351fea0efb5e69b195d5ff6d9518e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
